sudo: false
language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
matrix:
  include:
  - os: linux
dist: trusty

before_deploy: ./build_tools/travis/after_success.sh

deploy:
  provider: gcs
  access_key_id:
    secure: gfi7Ccu6wrIxlaRJtyEMoFqmHybbk9AW7FmHyR2F2YflHFRRgJT55kR83WwqEbznW+r7cgPhZf5MfauFdBqfaWetMwmLjGWaBEVb6hcB+a6sPuonSBQI5bNqRQh/Cv2a2kfHxEghJEVy2RpdWoOMWAydeSZX509K62+zwy/erQr0Er5lTvP/3xiN/dRFxJAxQvQ4lAJBGAycx/r5KIzKPU2RA33kZNaoHoTujZDDd4/JLowCtLG8dZqq60ZnKeEmPY6HaLERfGZy54dngiayEdzV9BCIgagWx61t4RkqQ/7XkH5DYRnFYb6F7IzXrTxW84MVMwIa8pQ6e1PmVsMMXzgfR2Rh8tsAzs4zyvoSfLjGJJRw4ADPvF7PEZNlkHs1kaLNPAfeEGWlJCxVxw2ws2aefQkF6V74mmsQperM/EWdQvNPMTovFFlvUqm+VBglp1DKorJisKlgRymLv3OOnmJULdZ0+XOWTOkqXQkcWgf4zLJiv0RaMoGrt62lZnoDHBiB67fR1H+rVJJ9uRFypSL+GwR9VOlSwhYofeAhANQNLAmOgNdmduOa+imR2GZl4q0PFFq1IVEjWXPVu0DY13LMFB47azn2d+y/0HYPZGSF/hwflSe3hACUHzfIKbRF4OxCGvoz8LviWwnR6HmQDHwzc8TVIqorZlTmR1dnLlg=
  secret_access_key:
    secure: LC/RKRNIxbOm4518Cjd0Dt3txIgSLlPK5jZsoDxpmNw02gzviUwMwodQqzGPy69hDcak9vi3P0ADPN1LPJLIxdtH8JMihQ9ooR4rQVyknjeII4flXhHlWkgc+i3KSNOLVj6dHY9BUXjnsv1bZDdKkgONOmF3FozTJaexrm993YWxsoU6klD7aeem3s2fpHlDuwoc03xiCLIlpDfSrZqJw/Gdvew0So6vpJRZIImYFjc7ibEON6gsXwGIX0j8NjhNhloHTfMvTiuI4APOVLtVmjD5BOA5E2zZAe5+FMG+3GGJps7POexhTEFhcZy2Iiy2VIrgaSvW0n2v1kMnYlQTJldrVEK+L0djNSHtUSDdre0DRR6+IkZuG0eqSfl4AD5lKydALKg/wzMOAfDFslVGlZDSsO2WZzzlYKKt0g41Tb9ivja2WQNhQJqGPQRin1OMt7SXyaw3X0UY5SFyF7hBFA3dgdd0C138JXODvEWoXCxzIWnD5nM/y2WWvR8O0FaOPDEJWxy3VH5KNesmhvdZD6uK0XNcTYk6ovcPUot3m2iokkD6H1B2d4tncNApEIoTnqHCxRQA8UBqzobZge6xz3OM72JxCpLz+ATXuLyEuQY8WAsMYP9C4r/BRY6DYAb/696eYsx8kFavvlTO4+7wc/ALpISKhNBBDO3b6HbsjSY=
  bucket: morpheo_analytics
  local-dir: artifacts
  acl: public-read
  skip_cleanup: true
  on:
    repo: tguillemot/morpheo-analytics
